/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jash
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    JPanel panel;
    public Login() {
        initComponents();
        fullscreen_panel= new JPanel();
        fullscreen_panel.setBounds(0, 0,1000 ,1000 );
        fullscreen_panel.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fullscreen_panel = new javax.swing.JPanel();
        other_panel = new javax.swing.JPanel();
        selectuser_label = new javax.swing.JLabel();
        manager_button = new javax.swing.JRadioButton();
        customer_button = new javax.swing.JRadioButton();
        selectuser_label1 = new javax.swing.JLabel();
        selectuser_label2 = new javax.swing.JLabel();
        login_txt = new javax.swing.JTextField();
        clear_button = new javax.swing.JButton();
        newuser_button = new javax.swing.JButton();
        login_button = new javax.swing.JButton();
        password_txt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullscreen_panel.setBackground(new java.awt.Color(153, 153, 153));
        fullscreen_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)));

        other_panel.setBackground(new java.awt.Color(0, 255, 204));
        other_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102), 3));
        other_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectuser_label.setBackground(new java.awt.Color(102, 255, 102));
        selectuser_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        selectuser_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectuser_label.setText("Please Select Type of User");
        selectuser_label.setOpaque(true);
        other_panel.add(selectuser_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 24, 295, 38));

        manager_button.setBackground(new java.awt.Color(153, 51, 255));
        buttonGroup1.add(manager_button);
        manager_button.setText("Manager");
        other_panel.add(manager_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 88, -1, -1));

        customer_button.setBackground(new java.awt.Color(153, 51, 255));
        buttonGroup1.add(customer_button);
        customer_button.setText("Customer");
        customer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_buttonActionPerformed(evt);
            }
        });
        other_panel.add(customer_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 88, -1, -1));

        selectuser_label1.setBackground(new java.awt.Color(102, 255, 102));
        selectuser_label1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        selectuser_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectuser_label1.setText("Login ID");
        selectuser_label1.setOpaque(true);
        other_panel.add(selectuser_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 131, 170, 38));

        selectuser_label2.setBackground(new java.awt.Color(102, 255, 102));
        selectuser_label2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        selectuser_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectuser_label2.setText("Password");
        selectuser_label2.setOpaque(true);
        other_panel.add(selectuser_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 238, 170, 38));

        login_txt.setForeground(new java.awt.Color(204, 204, 204));
        login_txt.setText("Enter Login ID here");
        login_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_txtMouseClicked(evt);
            }
        });
        other_panel.add(login_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 131, 190, 38));

        clear_button.setBackground(new java.awt.Color(204, 0, 204));
        clear_button.setText("CLEAR");
        clear_button.setBorder(null);
        clear_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_buttonMouseClicked(evt);
            }
        });
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        other_panel.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 301, 67, 25));

        newuser_button.setBackground(new java.awt.Color(204, 0, 204));
        newuser_button.setText("New User? Click here to Register");
        newuser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuser_buttonActionPerformed(evt);
            }
        });
        other_panel.add(newuser_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 301, -1, -1));

        login_button.setBackground(new java.awt.Color(204, 0, 204));
        login_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login_button.setText("LOGIN");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        other_panel.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 344, 137, 47));

        password_txt.setForeground(new java.awt.Color(204, 204, 204));
        password_txt.setText("iiiiiiiiiiiii");
        password_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_txtMouseClicked(evt);
            }
        });
        other_panel.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 239, 190, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jash\\Pictures\\Boeings-New-Planes-are-Fuel-Savers.png")); // NOI18N
        other_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        title_label.setBackground(new java.awt.Color(153, 153, 255));
        title_label.setFont(new java.awt.Font("Segoe UI Semibold", 2, 30)); // NOI18N
        title_label.setForeground(new java.awt.Color(0, 102, 102));
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("WELCOME TO AIRLINE RESERVATION SYSTEM");
        title_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        title_label.setOpaque(true);

        javax.swing.GroupLayout fullscreen_panelLayout = new javax.swing.GroupLayout(fullscreen_panel);
        fullscreen_panel.setLayout(fullscreen_panelLayout);
        fullscreen_panelLayout.setHorizontalGroup(
            fullscreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullscreen_panelLayout.createSequentialGroup()
                .addGroup(fullscreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fullscreen_panelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fullscreen_panelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(other_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131))
        );
        fullscreen_panelLayout.setVerticalGroup(
            fullscreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullscreen_panelLayout.createSequentialGroup()
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(other_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(fullscreen_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_buttonActionPerformed

    private void login_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_txtMouseClicked
login_txt.setText("");
login_txt.setForeground(Color.black);
    }//GEN-LAST:event_login_txtMouseClicked

    private void password_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_txtMouseClicked
password_txt.setText("");
password_txt.setForeground(Color.black);

    }//GEN-LAST:event_password_txtMouseClicked

    private void clear_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_buttonMouseClicked

    }//GEN-LAST:event_clear_buttonMouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String login=login_txt.getText(),password=password_txt.getText();
        if(login.equals("") || login_txt.getForeground()!=Color.black)
{
    JOptionPane.showMessageDialog(null,"Enter Login ID");
    return;
}
    if(password.equals("")|| password_txt.getForeground()!=Color.black)
{
    JOptionPane.showMessageDialog(null,"Enter Password");
    return;
}
        if(!customer_button.isSelected() && !manager_button.isSelected())
{
    JOptionPane.showMessageDialog(null,"Select Customer or Manager");
    return;
}

        PreparedStatement ps;
        String query="SELECT `loginid`,`password`,`fname`,`usertype` FROM `user` WHERE `loginid` like ?";
        try
        {
            ps=MyConn.getConnection().prepareStatement(query);
            ps.setString(1,login);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                String usertype,loginid,pass,fname;
                usertype=rs.getString("usertype");
                loginid=rs.getString("loginid");
                pass=rs.getString("password");
                fname=rs.getString("fname");
   
                if((customer_button.isSelected() && usertype.equals("C")) ||( manager_button.isSelected() && usertype.equals("M")))
                {
                if(loginid.equals(login) && pass.equals(password))
                {
                        JOptionPane.showMessageDialog(null,"Successfully Logged On");
                        NewJFrame j=new NewJFrame(loginid,usertype,fname);
                        j.setVisible(true);
                        this.setVisible(false);
                        j.pack();
                        j.setLocationRelativeTo(null);
                        j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        j=null;
                        return;
                }
                }
            }
            JOptionPane.showMessageDialog(null,"Incorrect Credentials");

        }
        catch(SQLException e)
        {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_login_buttonActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
     password_txt.setText("");
login_txt.setText("");
buttonGroup1.clearSelection();
   // TODO add your handling code here:
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void newuser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuser_buttonActionPerformed
Registration r=new Registration();
r.setVisible(true);
this.setVisible(false);
r=null;// TODO add your handling code here:
    }//GEN-LAST:event_newuser_buttonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear_button;
    private javax.swing.JRadioButton customer_button;
    private javax.swing.JPanel fullscreen_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField login_txt;
    private javax.swing.JRadioButton manager_button;
    private javax.swing.JButton newuser_button;
    private javax.swing.JPanel other_panel;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JLabel selectuser_label;
    private javax.swing.JLabel selectuser_label1;
    private javax.swing.JLabel selectuser_label2;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
